---
- name: Create tls location if that need
  file: 
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: bareos
    group: bareos
  with_items:
    - "/etc/bareos/tls"

- name: Configure bareos-fd clients
  no_log: true
  when: bareos_fd.client is defined
  template:
    src: client.conf.j2
    dest: /etc/bareos/bareos-fd.d/client/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_fd.client }}"
  notify:
    - restart bareos-fd service
