---
- name: Update repo cache and install a few prerequisite packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - apt-transport-https
    - gnupg2

- name: Add official Bareos package authentication key
  apt_key:
    keyserver: "{{ bareos_keyserver }}"
    id: "{{ bareos_apt_key }}"
    state: present

- name: Add the Bareos repository to APT sources
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: bareos
    mode: '0644'
  with_items:
    - "deb https://download.bareos.org/bareos/release/{{ bareos_release }}/Debian_{{ ansible_distribution_major_version }} /"

- name: Install Bareos File Daemon
  apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  with_items:
    - bareos-filedaemon
  notify:
    - enable bareos-fd service
    - restart bareos-fd service
