---
- ansible.builtin.include_tasks: "{{ role_path }}/tasks/redhat/install.yml"
  tags:
    - install_bareos_fd
    - install
    - bareos_fd

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/redhat/director.yml"
  when: bareos_fd.director is defined
  tags:
    - configure_bareos_fd
    - bareos_fd_director
    - bareos_fd

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/redhat/client.yml"
  when: bareos_fd.client is defined
  tags:
    - configure_bareos_fd
    - bareos_fd_client
    - bareos_fd

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/redhat/percona-xtrabackup.yml"
  when: bareos_fd.percona_xtrabackup is defined
  tags:
    - configure_bareos_fd
    - bareos_fd_percona_xtrabackup
    - bareos_fd

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/redhat/hashicorp.yml"
  when: bareos_fd.hashicorp_vault is defined
  tags:
    - configure_bareos_fd
    - bareos_fd_hashicorp
    - bareos_fd

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/redhat/messages.yml"
  when: bareos_fd.messages is defined
  tags:
    - configure_bareos_fd
    - bareos_fd_messages
    - bareos_fd

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/redhat/client_dir.yml"
  when: bareos_server is defined
  tags:
    - configure_bareos_dir
    - bareos_dir_client
    - bareos_dir
