---
- name: Converge
  hosts: all
  tasks:
    - name: Install requirements for RedHat
      when: ansible_os_family == 'RedHat'
      ansible.builtin.yum:
        name: gnupg
        state: present
        update_cache: true
    - name: "Include leadlineit.bareos_fd"
      ansible.builtin.include_role:
        name: "leadlineit.bareos_fd"
