---
dependency:
  name: galaxy
provisioner:
  name: ansible
verifier:
  name: ansible
driver:
  name: docker
platforms:
  - name: instance-centos
    image: "6nsh/centos:${MOLECULE_DISTRO:-stream8}-ansible"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
