---
# handlers file for leadlineit.bareos_fd

- name: enable bareos-fd service
  service:
    name: bareos-fd
    enabled: true

- name: restart bareos-fd service
  service:
    name: bareos-fd
    state: restarted
