---
- name: enable bareos-fd service
  ansible.builtin.service:
    name: bareos-fd
    enabled: true

- name: restart bareos-fd service
  ansible.builtin.service:
    name: bareos-fd
    state: restarted
