---
- name: Update repo cache and install a few prerequisite packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - apt-transport-https
    - gnupg2

- name: Add official Bareos package authentication key
  ansible.builtin.apt_key:
    keyserver: "{{ bareos_keyserver }}"
    id: "{{ bareos_apt_key }}"
    state: present

- name: Add the Bareos repository to APT sources for Debian 9.0
  when: ansible_distribution_release == "stretch"
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    filename: bareos
    mode: '0644'
  with_items:
    - "deb https://download.bareos.org/bareos/release/{{ bareos_release }}/Debian_9.0 /"

- name: Add the Bareos repository to APT sources for Debian 10/11
  when: ansible_distribution_release != "stretch"
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    filename: bareos
    mode: '0644'
  with_items:
    - "deb https://download.bareos.org/bareos/release/{{ bareos_release }}/Debian_{{ ansible_distribution_major_version }} /"

- name: Install Bareos File Daemon
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - bareos-filedaemon
  notify:
    - Enable bareos-fd service
    - Restart bareos-fd service
