---
- name: Update repo cache and install a few prerequisite packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - apt-transport-https
    - gnupg2

- name: Add official Bareos package authentication key
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "https://download.bareos.org/current/Debian_{{ ansible_distribution_major_version }}/Release.key"

- name: Add the Bareos repository to APT sources for Debian 10/11/12
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    filename: bareos
    mode: '0644'
  with_items:
    - "deb https://download.bareos.org/current/Debian_{{ ansible_distribution_major_version }} /"

- name: Install Bareos-FD
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - bareos-filedaemon
  notify:
    - Enable bareos-fd service
    - Restart bareos-fd service
