---
- name: Configure bareos-fd messages
  ansible.builtin.template:
    src: messages.conf.j2
    dest: /etc/bareos/bareos-fd.d/messages/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_fd.messages }}"
  notify:
    - Restart bareos-fd service

- name: Find unmanaged Bareos messages configurations
  ansible.builtin.find:
    paths: /etc/bareos/bareos-fd.d/messages
    file_type: file
    excludes: "{{ bareos_fd.messages | map(attribute='name') | product(['.conf']) | map('join') | flatten }}"
  register: ffout

- name: Remove unmanaged Bareos messages configurations
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ffout.files | map(attribute='path') | unique }}"
  notify:
    - Restart bareos-fd service
