---
- name: Update repo cache and install a few prerequisite packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - xz-utils

- name: Wget percona-release and install it with dpkg
  ansible.builtin.apt:
    deb: "{{ item }}"
  with_items:
    - "https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb"

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check and set version of mysql-community-server
  ansible.builtin.set_fact:
    mysql_version: "{{ ansible_facts.packages['mysql-community-server'] | map(attribute='version') | map('split','.') | map(attribute='0') }}"

- name: Enable tools for percona-release
  ansible.builtin.command: percona-release enable-only tools
  changed_when: false

- name: Install Percona XtraBackup 2.4 with Bareos plugin and qpress
  when: mysql_version[0] == "5"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - bareos-filedaemon-percona-xtrabackup-python-plugin
    - percona-xtrabackup-24
    - qpress
  notify:
    - restart bareos-fd service

- name: Install Percona XtraBackup 8.0 with Bareos plugin and qpress
  when: mysql_version[0] == "8"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - bareos-filedaemon-percona-xtrabackup-python-plugin
    - percona-xtrabackup-80
    - qpress
  notify:
    - restart bareos-fd service
