---
- name: Update repo cache and add percona-release repo with yum
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
    update_cache: true
  with_items:
    - "https://repo.percona.com/yum/percona-release-latest.noarch.rpm"

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check and set version of mysql-community-server if exist
  when: "'mysql-community-server' in ansible_facts.packages"
  ansible.builtin.set_fact:
    mysql_version: "{{ ansible_facts.packages['mysql-community-server'] | map(attribute='version') | map('split','.') | map(attribute='0') }}"

- name: Check and set version of mysql-common if exist
  when: "'mysql-common' in ansible_facts.packages"
  ansible.builtin.set_fact:
    mysql_version: "{{ ansible_facts.packages['mysql-common'] | map(attribute='version') | map('split','.') | map(attribute='0') }}"

- name: Set mysql_version for percona-server-server-57 if exist
  when: "'Percona-Server-server-57' in ansible_facts.packages"
  ansible.builtin.set_fact:
    mysql_version: "5"

- name: Set mysql_version for percona-server-server if exist
  when: "'percona-server-server' in ansible_facts.packages"
  ansible.builtin.set_fact:
    mysql_version: "8"

- name: Enable tools for percona-release
  ansible.builtin.command: percona-release enable-only tools
  changed_when: false

- name: Install Percona XtraBackup 2.4 with Bareos plugin and qpress
  when: mysql_version[0] == "5"
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - bareos-filedaemon-percona-xtrabackup-python-plugin
    - percona-xtrabackup-24
    - qpress
  notify:
    - restart bareos-fd service

- name: Install Percona XtraBackup 8.0 with Bareos plugin and qpress
  when: mysql_version[0] == "8"
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - bareos-filedaemon-percona-xtrabackup-python-plugin
    - percona-xtrabackup-80
    - qpress
  notify:
    - restart bareos-fd service
